variables:
  - name: TARGET_REPO
    default: oci://ghcr.io/defenseunicorns/packages/uds

  - name: VERSION
    description: "The version of the packages to build"
    # x-release-please-start-version
    default: "0.1.2"
    # x-release-please-end

tasks:
  - name: package
    description: "Build and publish the UDS package"
    actions:
      - description: "Create the Zarf Packages"
        cmd: |
          ZARF_ARCHITECTURE=amd64 ./uds run create-package --no-progress
          ZARF_ARCHITECTURE=arm64 ./uds run create-package --no-progress

      - description: "Publish the packages"
        cmd: |
          ./uds zarf package publish zarf-package-pod-identity-webhook-arm64-${VERSION}.tar.zst ${TARGET_REPO}
          ./uds zarf package publish zarf-package-pod-identity-webhook-amd64-${VERSION}.tar.zst ${TARGET_REPO}
