tasks:
  - name: k3d-test-cluster
    actions:
      - description: "Create the K3d cluster"
        # renovate: datasource=github-tags depName=defenseunicorns/uds-k3d versioning=semver
        cmd: "zarf package deploy oci://defenseunicorns/uds-k3d:0.2.1-multi --confirm --no-progress"
