includes:
  - create: ./tasks/create.yaml
  - setup: ./tasks/setup.yaml
  - deploy: ./tasks/deploy.yaml

tasks:
  - name: package
    description: "Build and test the package"
    actions:
      - task: create:package
      - task: setup:k3d-test-cluster
      - task: deploy:package
