apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-identity-webhook
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-identity-webhook
  template:
    metadata:
      labels:
        app: pod-identity-webhook
    spec:
      serviceAccountName: pod-identity-webhook
      containers:
      - name: pod-identity-webhook
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
        imagePullPolicy: Always
        command:
        - /webhook
        - --in-cluster=false
        - --namespace=kube-system
        - --service-name=pod-identity-webhook
        - --annotation-prefix=irsa
        - --token-audience=irsa
        - --logtostderr
        volumeMounts:
        - name: cert
          mountPath: "/etc/webhook/certs"
          readOnly: true
      volumes:
      - name: cert
        secret:
          secretName: pod-identity-webhook-cert
