apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: patch-mutating-webhook-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace}}
roleRef:
  kind: ClusterRole
  name: patch-mutating-webhook-cluster-role
  apiGroup: rbac.authorization.k8s.io
